---
env:
  commonjs: true
  es6: true
  node: true

parser: "@typescript-eslint/parser"

plugins: [ '@typescript-eslint', 'eslint-plugin-node' ]

parserOptions:
  emcaVersion: 2020
  sourceType: module

rules:
  indent: [ "error", "tab" ]
