---
env:
  commonjs: true
  es6: true
  node: true

parser: "@typescript-eslint/parser"

plugins: [ '@typescript-eslint', 'eslint-plugin-node' ]

parserOptions:
  emcaVersion: 2020
  sourceType: module

rules:
  # disabled for now, since there's no option for double-indent on continued line
  # indent: [ "error", "tab" ]
  indent: off
